// <auto-generated />
using Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    partial class FlightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Flight.Models.FlightModel", b =>
                {
                    b.Property<int>("FlightModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightModelId");

                    b.ToTable("FlightModel");

                    b.HasData(
                        new
                        {
                            FlightModelId = 1,
                            Date = "2/15/2026",
                            FlightNumber = "UA3321",
                            From = "Chicago",
                            Price = 235,
                            To = "New York"
                        },
                        new
                        {
                            FlightModelId = 2,
                            Date = "3/1/2026",
                            FlightNumber = "QA1078",
                            From = "Dubai",
                            Price = 590,
                            To = "London"
                        },
                        new
                        {
                            FlightModelId = 3,
                            Date = "6/15/2026",
                            FlightNumber = "UA3321",
                            From = "Hong Kong",
                            Price = 900,
                            To = "San Francisco"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
